2021-11-03 06:35:33 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-03 06:35:33 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration yandex_station which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-03 06:35:33 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-03 06:35:33 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration xiaomi_miot_raw which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-03 06:35:35 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=183 from 2021-11-02 16:33:47)
2021-11-03 06:35:47 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f908508bb080000e4205e03b47b19d915262833665697d0d10c4fb4649471626 from 192.168.1.150
2021-11-03 06:35:47 ERROR (MainThread) [homeassistant.components.vacuum] xiaomi_miot_raw: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 618, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot_raw/basic_dev_class.py", line 438, in async_update
    if r['code'] == 0:
TypeError: string indices must be integers
2021-11-03 06:35:47 ERROR (SyncWorker_4) [xiaomi_gateway] The device with sid 158d0006d49f34 isn't supported of the used gateway firmware. Please update the gateway firmware if possible! This is the only way the issue can be solved.
2021-11-03 06:35:48 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f908508bb080000e4205e03b47b19d915262833665697d0d10c4fb4649471626 from 192.168.1.150
2021-11-03 06:35:48 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f908508bb080000e4205e03b47b19d915262833665697d0d10c4fb4649471626 from 192.168.1.150
2021-11-03 06:35:48 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f908508bb080000e4205e03b47b19d915262833665697d0d10c4fb4649471626 from 192.168.1.150
2021-11-03 06:35:55 WARNING (MainThread) [homeassistant.components.vacuum] Setup of vacuum platform xiaomi_miio is taking over 10 seconds.
2021-11-03 06:35:57 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ (states('sensor.pressure_158d0001dc32b4')|float * 0.75 + 4)|round(1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-11-03 06:35:57 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ (states('sensor.pressure_158d0001dc32b4')|float * 0.75 + 4)|round(1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-11-03 15:14:33 ERROR (Thread-5) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/xiaomi_gateway/__init__.py", line 180, in _listen_to_msg
    data, (ip_add, _) = self._mcastsocket.recvfrom(SOCKET_BUFSIZE)
OSError: [Errno 9] Bad file descriptor
2021-11-03 15:14:34 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
